# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e43bd5e7c12f8f766c9fb4cfec82be5322c0b6fceea6dbc2eaf307665eed329d5a79ac987d519b736c73f0420b600a18be25b0f4d74191e2cbe826c3a46fea4

test:
  secret_key_base: b8d74a0ba5f4b5fc964fe1da515948920bfd8f8a1b26e0229b3137b4fd317afe6cfd60be683f62c1f436a89381d93a495c87e0bc6fd9fef7849483ccdaf15f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
